FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
# SSL configuration can be added if needed, but for Coolify/Traefik upstream, we typically just need HTTP or mount provided certs.
# COPY ssl /etc/nginx/ssl
